// <auto-generated />
using System;
using Airplane.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Airplane.Infra.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20181025013221_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Airplane.Domain.Entities.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity")
                        .HasColumnName("Capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreateadAt");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Model");

                    b.HasKey("Id");

                    b.ToTable("Airplane");
                });
#pragma warning restore 612, 618
        }
    }
}
